// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  fields: string;
  form: string;
  hint: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
