// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  layout: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
