// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  badge: string;
  over: string;
  within: string;
}
declare const cssExports: CssExports;
export default cssExports;
