// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  mark: string;
  status: string;
}
declare const cssExports: CssExports;
export default cssExports;
