// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  aside: string;
  back: string;
  header: string;
  row: string;
  subtitle: string;
  title: string;
  titles: string;
}
declare const cssExports: CssExports;
export default cssExports;
