// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cell: string;
  header: string;
  numeric: string;
  scroll: string;
  table: string;
}
declare const cssExports: CssExports;
export default cssExports;
