// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  back: string;
  notFound: string;
}
declare const cssExports: CssExports;
export default cssExports;
