// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  notice: string;
  unknown: string;
}
declare const cssExports: CssExports;
export default cssExports;
