// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  group: string;
  legend: string;
  option: string;
  unavailable: string;
}
declare const cssExports: CssExports;
export default cssExports;
