// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  conversion: string;
  glyph: string;
  hint: string;
  markers: string;
  note: string;
  overCapacity: string;
  panel: string;
  partiallyPriced: string;
  title: string;
  unpriced: string;
  workings: string;
}
declare const cssExports: CssExports;
export default cssExports;
