// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  marker: string;
  markers: string;
  overCapacity: string;
  partiallyPriced: string;
  unpriced: string;
  visuallyHidden: string;
}
declare const cssExports: CssExports;
export default cssExports;
