// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  body: string;
  lead: string;
  months: string;
}
declare const cssExports: CssExports;
export default cssExports;
