// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  control: string;
  error: string;
  field: string;
  hint: string;
  label: string;
  visuallyHidden: string;
}
declare const cssExports: CssExports;
export default cssExports;
