// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  dialog: string;
  form: string;
  legend: string;
  option: string;
  picker: string;
  reason: string;
  target: string;
}
declare const cssExports: CssExports;
export default cssExports;
