// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  failed: string;
  loading: string;
}
declare const cssExports: CssExports;
export default cssExports;
