// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  current: string;
  empty: string;
  section: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
