// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  heading: string;
  list: string;
  readout: string;
  verdict: string;
}
declare const cssExports: CssExports;
export default cssExports;
