// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  error: string;
  info: string;
  message: string;
  warning: string;
}
declare const cssExports: CssExports;
export default cssExports;
