// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  failedDetail: string;
  failedTitle: string;
  loading: string;
  panel: string;
}
declare const cssExports: CssExports;
export default cssExports;
