// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cell: string;
  editor: string;
  empty: string;
  field: string;
  hint: string;
  input: string;
  problem: string;
  value: string;
}
declare const cssExports: CssExports;
export default cssExports;
