// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  count: string;
  empty: string;
  plain: string;
  register: string;
  toolbar: string;
}
declare const cssExports: CssExports;
export default cssExports;
