// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  action: string;
  entry: string;
  list: string;
  more: string;
  reason: string;
}
declare const cssExports: CssExports;
export default cssExports;
