// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  empty: string;
  grid: string;
  head: string;
  label: string;
  labelContent: string;
  name: string;
  node: string;
  numeric: string;
  person: string;
  project: string;
  scroll: string;
  toggle: string;
  total: string;
  twisty: string;
  value: string;
  visuallyHidden: string;
  widget: string;
}
declare const cssExports: CssExports;
export default cssExports;
