// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  link: string;
  nav: string;
}
declare const cssExports: CssExports;
export default cssExports;
