// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  body: string;
  close: string;
  dialog: string;
  header: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
