// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bad: string;
  good: string;
  readout: string;
}
declare const cssExports: CssExports;
export default cssExports;
