// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  entry: string;
  failed: string;
  idle: string;
  loading: string;
  name: string;
  ready: string;
  remote: string;
  remotes: string;
  strip: string;
  url: string;
}
declare const cssExports: CssExports;
export default cssExports;
