// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  cell: string;
  fields: string;
  form: string;
}
declare const cssExports: CssExports;
export default cssExports;
