// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  links: string;
  screen: string;
}
declare const cssExports: CssExports;
export default cssExports;
